<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="1">

  <testsuite name="functional.testcase3"
    errors="0" failures="1" hostname="" id="" package="functional" skipped="0"
    tests="1" time="20.05" timestamp="Tue, 23 May 2017 01:01:21 GMT">
  
    <testcase name="test RebelHanger Full order 2 - updates in cart" classname="functional.testcase3" time="20.05" assertions="15">

    

    

    

    

    

    

    

    

    

    

    

    

    

      <failure message="Testing if element &lt;//*[@id=&quot;fb-ot&quot;]&gt; contains text: &quot;Order Total: 36.30&quot;.">    at Object.test RebelHanger Full order 2 - updates in cart (C:\Users\Harvey\Desktop\git_xuelflol\hoth\test\functional\testcase3.js:113:15)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)</failure>

    
    </testcase>
  
  
  </testsuite>
</testsuites>
